apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mjr54hrzu-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/mjr54hrzu-dotnet-basic